# Generated by Django 4.0 on 2022-10-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=128)),
                ('certificate_issuer', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('PRF', 'Professional'), ('LDR', 'Leadership'), ('VLT', 'Volunteer')], default='PRF', max_length=3)),
                ('experience_name', models.CharField(max_length=128)),
                ('experience_description', models.TextField()),
                ('experience_start_date', models.DateField()),
                ('experence_end_date', models.DateField(blank=True)),
                ('experience_skills', models.CharField(max_length=256)),
            ],
        ),
    ]
