# Generated by Django 4.0 on 2022-11-02 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_certification_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_company',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
