# Generated by Django 4.0 on 2022-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_experience_experience_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experence_end_date',
            field=models.DateField(),
        ),
    ]
